version: "3.3"
services:
  app:
    build: .
    container_name: app-cad-renderer
    command: tail -f /dev/null
    volumes:
      - ./:/app
    ports:
      - "5002:5002"
    entrypoint: [ "sh", "-c", "python /app/run.py" ]

